### PR TITLE
Fix routing response when cluster is empty

### LINKED ISSUE #53: Better failure handling when no storage servers exist
When there are no storage servers, the routing node fails with a floating point exception because it tries to hash into the global hash ring when the ring is empty. It just prints out `error!`, and the routing process fails silently. This is obviously bad, and we should instead return a more useful error message to the user.

### PR DESCRIPTION
**Pull request by vsreekanti**
* Routing layer now returns an error code if the cluster is empty.
* User & benchmark nodes (via `get_address_from_routing`) will wait & repeatedly query the routing layer while there are no storage servers.
* Remove brittle log grep-ing from `simple_test.sh`.

Fixes #53.

### CODE REVIEW

File: src/bedrock/hash_ring.cpp [hunk 1]
```diff
@@ -165,25 +166,46 @@ vector<string> get_address_from_routing(
...
+
+    rid += 1;
+
+    // query routing for addresses on the other tier
+    key_response = send_request<communication::Key_Request, communication::Key_Response>(key_req, sending_socket, receiving_socket, succeed);
+
+    if (!succeed) {
+      return result;
+    } else {
+      cerr << "No servers have joined the cluster yet. Retrying request." << endl;
```
Comment (cw75) [inline src/bedrock/hash_ring.cpp]: why do we always print this error msg? Seems like if error number is 0 we are fine?

Comment (vsreekanti) [reply src/bedrock/hash_ring.cpp]: Good call... fixing that. 😄
